schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://bao-development.myshopify.com/admin/api/2023-07/graphql.json
      headers:
        X-Shopify-Access-Token:
      introspect: true
